# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37e3aa054685a5787f1c31d6ac7e85239ecb4d86963c7fd9726c785ecbd0d88666fbda4e3c3a69d68170b861736cbb485fc145c264d215947ef9b0fa88435507

test:
  secret_key_base: 9e6f0bb9ec44025c30156fe005d87a6dcc53d92ab83b6f58699bb2cd0b0ec1307179b1fb583d839113832dad103d67382ded8b57b6a1a844ec7b86b154ac7252

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
